// Tradução dos códigos oficiais (ANEXO_I, abas RN_RECEPCAO_DPS e RN DPS_NFS-e)
// para linguagem comum, com o próximo passo. Códigos sem tradução mostram a
// descrição oficial — nunca escondemos o motivo real.
const T = {
  E0006: ['O ambiente (teste/produção) da nota não confere com o servidor da Receita.', 'Avise o suporte do NotaVez.'],
  E0008: ['O horário da nota ficou à frente do horário da Receita.', 'Tente de novo em alguns minutos.'],
  E0010: ['A série da nota não é permitida para aplicativos próprios.', 'Ajuste a série no seu perfil (1 a 49999).'],
  E0014: ['Já existe uma nota com esta numeração.', 'Não emita de novo: vamos consultar a nota existente.'],
  E0015: ['A data da competência é posterior à data de emissão.', 'Escolha a data em que o serviço foi prestado (hoje ou antes).'],
  E0016: ['A competência é anterior à adesão do município ao Sistema Nacional.', 'Confira a data da competência ou emita pelo sistema da prefeitura.'],
  E0037: ['O município do seu CNPJ não é conveniado ao Sistema Nacional da NFS-e.', 'Emita pelo sistema da prefeitura.'],
  E0038: ['O convênio do município com o Sistema Nacional não está ativo.', 'Emita pelo sistema da prefeitura.'],
  E0039: ['O município do seu CNPJ não liberou os emissores nacionais.', 'Emita pelo sistema da prefeitura.'],
  E0041: ['O município do perfil não é o do endereço do seu CNPJ de MEI.', 'Corrija o município no perfil.'],
  E0084: ['O município do perfil não corresponde ao endereço do CNPJ nem ao cadastro municipal.', 'Corrija o município no perfil.'],
  E0116: ['A prefeitura exige a sua inscrição municipal na nota.', 'Informe a inscrição municipal em Perfil › Opções avançadas.'],
  E0119: ['A inscrição municipal informada não está autorizada a emitir NFS-e.', 'Confira a inscrição municipal com a prefeitura.'],
  E0120: ['A prefeitura não tem cadastro complementar para você: a inscrição municipal não deve ir na nota.', 'Apague a inscrição municipal em Perfil › Opções avançadas.'],
  E0166: ['Falta informar como a empresa apura os tributos no Simples.', 'Escolha o regime de apuração em Perfil.'],
  E0175: ['Com tudo apurado pelo Simples, o regime especial deve ser "Nenhum".', 'Avise o suporte do NotaVez.'],
  E0080: ['O CNPJ do emitente é inválido.', 'Confira o CNPJ do perfil.'],
  E0082: ['A Receita não encontrou o seu CNPJ na data da competência.', 'Confira o CNPJ e a data da competência.'],
  E0121: ['A nota foi enviada com o seu nome, e a Receita não aceita.', 'Avise o suporte do NotaVez.'],
  E0174: ['Para MEI, o regime especial deve ser "Nenhum".', 'Avise o suporte do NotaVez.'],
  E0188: ['O CNPJ do cliente é inválido.', 'Corrija o CNPJ no cadastro do cliente.'],
  E0190: ['A Receita não encontrou o CNPJ do cliente.', 'Confira o CNPJ no cadastro do cliente.'],
  E0202: ['O cliente não pode ser o seu próprio CNPJ.', 'Escolha outro cliente.'],
  E0206: ['O CPF do cliente é inválido.', 'Corrija o CPF no cadastro do cliente.'],
  E0207: ['A Receita não encontrou o CPF do cliente.', 'Confira o CPF no cadastro do cliente.'],
  E0235: ['Cliente com CNPJ precisa de endereço completo.', 'Complete o endereço no cadastro do cliente.'],
  E0240: ['O CEP do cliente não pertence ao município informado.', 'Corrija o CEP ou o município do cliente.'],
  E0310: ['O código do serviço não existe na lista nacional.', 'Escolha outro serviço.'],
  E0204: ['Para o cliente reter o ISS, ele precisa estar identificado na nota.', 'Escolha o cliente ou desmarque a retenção.'],
  E0583: ['MEI não pode ter ISS retido.', 'Avise o suporte do NotaVez.'],
  E0595: ['A alíquota do ISS não pode passar de 5%.', 'Corrija a alíquota.'],
  E0621: ['Com ISS retido, a alíquota do ISS no Simples precisa constar na nota (mínimo 1,8%).', 'Informe a alíquota na nota ou no Perfil.'],
  E0625: ['Sem retenção, a alíquota não deve ir na nota (o ISS é pago no DAS).', 'Avise o suporte do NotaVez.'],
  E0628: ['Com ISS retido, a alíquota precisa constar na nota (mínimo 1,8%).', 'Informe a alíquota na nota ou no Perfil.'],
  E0631: ['Sem retenção, a alíquota não deve ir na nota.', 'Avise o suporte do NotaVez.'],
  E0635: ['O município calcula o ISS pela alíquota cadastrada: ela não deve ir na nota.', 'Avise o suporte do NotaVez.'],
  E0640: ['O município não é conveniado: a alíquota do ISS precisa constar na nota.', 'Informe a alíquota do ISS do município.'],
  E0667: ['O município não autoriza este cliente (pessoa física) a reter o ISS.', 'Desmarque a retenção.'],
  E0600: ['MEI não informa alíquota de ISS.', 'Avise o suporte do NotaVez.'],
  E0676: ['MEI não informa tributos federais na nota.', 'Avise o suporte do NotaVez.'],
  E0617: ['O município calcula o ISS pela alíquota cadastrada: ela não deve ir na nota.', 'Avise o suporte do NotaVez.'],
  E0619: ['O município não é conveniado: a alíquota do ISS precisa constar na nota.', 'Informe a alíquota do ISS do município (Perfil ou nota).'],
  E0322: ['Com IBS/CBS, a nota precisa do código NBS do serviço.', 'Escolha a NBS na nota.'],
  E0678: ['Falta a base de cálculo do PIS/COFINS.', 'Confira a situação do PIS/COFINS no Perfil.'],
  E0680: ['A base do PIS/COFINS não foi aceita pela Receita.', 'Avise o suporte do NotaVez (regra E0680).'],
  E0684: ['Falta a alíquota do PIS.', 'Informe a alíquota do PIS no Perfil.'],
  E0690: ['Falta a alíquota da COFINS.', 'Informe a alíquota da COFINS no Perfil.'],
  E0694: ['O valor do PIS não confere com base × alíquota.', 'Avise o suporte do NotaVez.'],
  E0696: ['O valor da COFINS não confere com base × alíquota.', 'Avise o suporte do NotaVez.'],
  E0698: ['Falta o tipo de retenção de PIS/COFINS/CSLL.', 'Avise o suporte do NotaVez.'],
  E0699: ['O INSS retido deve ser maior que zero e menor que o valor do serviço.', 'Corrija o valor retido.'],
  E0700: ['O IRRF retido deve ser maior que zero e menor que o valor do serviço.', 'Corrija o valor retido.'],
  E0701: ['O valor retido de PIS/COFINS/CSLL deve ser maior que zero e menor que o valor do serviço.', 'Corrija o valor retido.'],
  E0713: ['Empresa fora do Simples não usa os campos de tributos do Simples.', 'Avise o suporte do NotaVez.'],
  E0720: ['Sem retenção marcada, não informe valor retido de PIS/COFINS/CSLL.', 'Marque o que foi retido ou apague o valor.'],
  E0724: ['Com retenção de PIS/COFINS/CSLL, informe o valor retido (somado).', 'Informe o valor retido.'],
  E0850: ['IBS/CBS só pode ser informado para competências a partir de 01/01/2026.', 'Confira a data da competência.'],
  E0901: ['O indicador de operação do IBS/CBS não existe na tabela oficial.', 'Escolha outra forma de prestação do serviço.'],
  E0958: ['A classificação tributária do IBS/CBS não vale para serviços.', 'Escolha outra classificação.'],
  E0959: ['A classificação tributária não pertence ao CST informado.', 'Avise o suporte do NotaVez.'],
  E0964: ['Esta classificação do IBS/CBS não admite o grupo de tributação regular.', 'Avise o suporte do NotaVez.'],
  E0965: ['Esta classificação do IBS/CBS exige o grupo de tributação regular, ainda não suportado.', 'Escolha outra classificação ou emita pelo Emissor Nacional.'],
  E0972: ['Esta classificação do IBS/CBS exige diferimento, ainda não suportado.', 'Escolha outra classificação ou emita pelo Emissor Nacional.'],
  E0712: ['Para ME/EPP, a nota precisa trazer o percentual aproximado de tributos do Simples.', 'Informe o percentual em Perfil.'],
  E0710: ['MEI não informa percentual do Simples Nacional.', 'Avise o suporte do NotaVez.'],
  E0714: ['A assinatura digital da nota não confere.', 'Reenvie o certificado digital no perfil.'],
  E0715: ['O certificado digital está vencido, revogado ou com cadeia inválida.', 'Renove ou reenvie o certificado A1.'],
  E0716: ['O certificado digital está fora do padrão aceito (ICP-Brasil com CNPJ/CPF).', 'Use um e-CNPJ A1 ICP-Brasil.'],
  E0717: ['A nota foi enviada sem assinatura.', 'Avise o suporte do NotaVez.'],
  E0718: ['A nota precisa ser assinada com o certificado do próprio emitente.', 'Envie o certificado A1 do CNPJ do perfil.'],
  E1200: ['O certificado de conexão foi recusado pela Receita.', 'Confira se é um e-CNPJ A1 ICP-Brasil válido.'],
  E1203: ['O certificado digital está vencido.', 'Renove o certificado A1.'],
  E1205: ['A cadeia do certificado não foi reconhecida.', 'Use um certificado ICP-Brasil.'],
  E1207: ['O certificado digital foi revogado.', 'Emita um novo certificado A1.'],
  E1208: ['O certificado não é ICP-Brasil.', 'Use um certificado ICP-Brasil.'],
  E1209: ['O certificado não tem CNPJ ou CPF.', 'Use um e-CNPJ A1.'],
  E1235: ['A nota não passou na validação de formato da Receita.', 'Avise o suporte do NotaVez.'],
};

export function explicar(m) {
  const t = T[m.codigo];
  return {
    codigo: m.codigo,
    oficial: m.descricao,
    complemento: m.complemento ?? null,
    mensagem: t ? t[0] : (m.descricao || 'A Receita recusou a nota.'),
    proximoPasso: t ? t[1] : 'Revise os dados da nota. Se o problema continuar, fale com o suporte.',
  };
}

export const MOTIVOS_NAO_ENVIADA = {
  conexao: 'Não conseguimos conectar com a Receita. Nada foi enviado.',
  autorizacao: 'A Receita não autorizou a conexão com o seu certificado. Nada foi emitido.',
  limite: 'A Receita pediu para aguardar antes de novos envios. Nada foi emitido.',
  requisicao: 'A Receita não aceitou o envio. Nada foi emitido.',
};
